### PR TITLE
Set response status code

### PR DESCRIPTION
**Pull request by dennisvdvliet**

### CODE REVIEW

**Comment by julik** [comment]
Maybe add a `payload:` kwarg then? So that we do not have both a payload pos argument and a keyword argument in one? Will be a breaking API change but we can adjust

**Comment by dennisvdvliet** [comment]
Adding the payload kwarg feels verbose to me. I think most of the time you just want send a response and no need to set a status code (or anything else).

What is the drawback of having both a pos and kw arg in one method definition?

**Comment by julik** [comment]
The drawback is small-ish but significant. Most of the time the thing-you-make-json will come as the first argument, and it will be a Hash. Therefore if you do a call without a `status:` keyword, can you tell me whether the method will do the right thing (knowing it also accepts keyword arguments)?

`json_response({error: "The word contained 500x more spaces than characters, status: 'bug_closed'})`

In this example, if `json_response` accepts a generic options Hash instead of strict kwargs, can you tell me what the behavior/handling of `status:` key will be?

**Comment by dennisvdvliet** [comment]
```ruby
def json_response(payload, status: 200)
	puts "Called with:"
	puts "-payload: " + payload.inspect
	puts "-status: " + status.to_s	
	{
		payload: payload,
		status: status
	}
end

if json_response('payload')[:status] != 200
	puts "Failed"
end


if json_response({payload: 'payload', status: 300}, status: 201)[:status] != 201
	puts "Failed"
end

if json_response({payload: 'payload', status: 300})[:status] != 200
	puts "Failed"
end

# This is the only situation where if you look at it quickly the results might be not what you expect
if json_response(payload: 'payload', status: 300)[:status] != 300
	puts "Failed"
end
```

**Comment by julik** [comment]
Ok then

**Pull request merged**
